'use client';
import {useState} from 'react';
import {assignDemoPin} from '@/lib/demo-pin';
import type {CatalogEmployee,CatalogItem,CatalogItemKind} from '@/lib/catalog-local';
import type {Locale} from '@/lib/i18n';
import type {SiteId} from '@/lib/production-model';

type Props={locale:Locale;site:SiteId;items:CatalogItem[];employees:CatalogEmployee[];onItems:(items:CatalogItem[])=>void;onEmployees:(people:CatalogEmployee[])=>void};
const allSites:SiteId[]=['htl','htw','htft'];
const labels={en:{products:'Products and ingredients',staff:'Team members',add:'Add',name:'Name',kind:'Use',finished:'Finished product · bag counts',ingredient:'Ingredient · production only',weight:'Standard bag weight (kg)',active:'Active',locations:'Available at locations',save:'Save',cancel:'Cancel',edit:'Edit',search:'Search products or ingredients...',searchStaff:'Search team members...',staffHint:'Choose a name when taking a count or registering production.',nameRequired:'Enter a name.',invalidWeight:'Finished products require a weight greater than zero.',duplicate:'This name already exists in the catalog.',none:'No matching entries',locRequired:'Choose at least one location.',browser:'Local browser draft only. Not saved to Firestore or shared between devices.',inactive:'Inactive',all:'All',confirmDelete:'Mark this entry inactive?',category:'Category',protein:'Protein',prepared:'Preparation',dairy:'Dairy',vegetable:'Vegetable',seasoning:'Seasoning',other:'Other',counting:'Countable',ingredientOnly:'Ingredient only',roles:'Team members for counts and production',pin:'Demo access PIN (4–6 digits)',pinHint:'Set a PIN to let this employee identify themselves on the shared monitor. Never use a real Toast PIN in this prototype.',duplicatePin:'PIN already assigned to another employee or reserved.',pinError:'PIN must contain 4–6 digits.',pinSaved:'Employee PIN stays in this browser only.'},es:{products:'Productos e ingredientes',staff:'Personal',add:'Agregar',name:'Nombre',kind:'Uso',finished:'Producto terminado · conteo de bolsas',ingredient:'Insumo · solo producción',weight:'Peso estándar de bolsa (kg)',active:'Activo',locations:'Disponible en unidades',save:'Guardar',cancel:'Cancelar',edit:'Editar',search:'Buscar productos o ingredientes...',searchStaff:'Buscar personal...',staffHint:'Selecciona a la persona al tomar un conteo o registrar producción.',nameRequired:'Escribe un nombre.',invalidWeight:'Los productos terminados necesitan un peso mayor que cero.',duplicate:'Ya existe un registro con ese nombre.',none:'Sin coincidencias',locRequired:'Selecciona al menos una unidad.',browser:'Borrador local de este navegador. No se guarda en Firestore ni se comparte entre dispositivos.',inactive:'Inactivo',all:'Todos',confirmDelete:'¿Marcar este registro como inactivo?',category:'Categoría',protein:'Proteína',prepared:'Preparación',dairy:'Lácteos',vegetable:'Vegetales',seasoning:'Condimentos',other:'Otros',counting:'Contable',ingredientOnly:'Solo insumo',roles:'Personal para conteos y producción',pin:'PIN de acceso de prueba (4–6 dígitos)',pinHint:'Asigna un PIN para que la persona se identifique en el monitor. No uses el PIN real de Toast en este prototipo.',duplicatePin:'El PIN ya corresponde a otra persona o está reservado.',pinError:'El PIN debe tener entre 4 y 6 dígitos.',pinSaved:'El PIN de prueba solo funciona en este navegador.'}} as const;
const categories=['protein','prepared','dairy','vegetable','seasoning','other'] as const;
const siteLabel:Record<SiteId,string>={htl:'HTL',htw:'HTW',htft:'HTFT'};
const newId=()=>`draft-${crypto.randomUUID()}`;
const isItem=(value:CatalogItem|CatalogEmployee):value is CatalogItem=>'category' in value && 'bagWeightKg' in value;
export default function CatalogAdmin({locale,site,items,employees,onItems,onEmployees}:Props){
 const s=labels[locale];const [section,setSection]=useState<'products'|'staff'>('products');const [q,setQ]=useState('');const [editing,setEditing]=useState<string|null>(null);const [name,setName]=useState('');const [kind,setKind]=useState<CatalogItemKind>('ingredient');const [category,setCategory]=useState<CatalogItem['category']>('other');const [weight,setWeight]=useState('');const [locations,setLocations]=useState<SiteId[]>([site]);const [active,setActive]=useState(true);const [error,setError]=useState('');const [employeePin,setEmployeePin]=useState('');
 function reset(){setEditing(null);setName('');setKind('ingredient');setCategory('other');setWeight('');setLocations([site]);setActive(true);setError('');setEmployeePin('');}
 function startItem(p?:CatalogItem){setSection('products');setEditing(p?.id??'new');setName(p?.name??'');setKind(p?.kind??'ingredient');setCategory(p?.category??'other');setWeight(p?.bagWeightKg?.toString()??'');setLocations(p?.siteIds??[site]);setActive(p?.active??true);setError('');setEmployeePin('');}
 function startEmployee(p?:CatalogEmployee){setSection('staff');setEditing(p?.id??'new');setName(p?.name??'');setLocations(p?.siteIds??[site]);setActive(p?.active??true);setError('');setEmployeePin('');}
 async function submit(){const trimmed=name.trim();if(!trimmed){setError(s.nameRequired);return}if(!locations.length){setError(s.locRequired);return}const arr=section==='products'?items:employees;if(arr.some(x=>x.name.toLocaleLowerCase()===trimmed.toLocaleLowerCase()&&x.id!==editing)){setError(s.duplicate);return}if(section==='products'){
  const n=Number(weight);if(kind==='finished'&&(!Number.isFinite(n)||n<=0)){setError(s.invalidWeight);return}
  const value:CatalogItem={id:editing==='new'?newId():editing!,name:trimmed,kind,category,bagWeightKg:kind==='finished'?n:null,siteIds:locations,active};onItems(editing==='new'?[...items,value]:items.map(x=>x.id===editing?value:x));
 }else{if(editing==='new'&&!employeePin){setError(s.pinError);return;}const value:CatalogEmployee={id:editing==='new'?newId():editing!,name:trimmed,siteIds:locations,active};if(employeePin){try{await assignDemoPin(value.id,employeePin);}catch(e){setError(e instanceof Error && e.message==='DUPLICATE_PIN'?s.duplicatePin:s.pinError);return;}}onEmployees(editing==='new'?[...employees,value]:employees.map(x=>x.id===editing?value:x));}reset();}
 const data=(section==='products'?items:employees).filter(p=>p.name.toLocaleLowerCase().includes(q.trim().toLocaleLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
 return <div className="catalog-admin">
   <div className="catalog-tabs"><button className={section==='products'?'selected':''} onClick={()=>{setSection('products');setEditing(null);setQ('')}}>{s.products} ({items.length})</button><button className={section==='staff'?'selected':''} onClick={()=>{setSection('staff');setEditing(null);setQ('')}}>{s.staff} ({employees.length})</button></div>
   <div className="catalog-controls"><input aria-label={section==='products'?s.search:s.searchStaff} placeholder={section==='products'?s.search:s.searchStaff} value={q} onChange={e=>setQ(e.target.value)}/><button className="primary" onClick={()=>section==='products'?startItem():startEmployee()}>+ {s.add}</button></div>
   <p className="footnote">{section==='staff'?s.staffHint:s.browser}</p>
   {editing!==null&&<div className="catalog-editor"><h3>{s[section]}</h3><div className="field-grid"><label>{s.name}<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label>{section==='staff'&&<label>{s.pin}<input type="password" inputMode="numeric" autoComplete="new-password" maxLength={6} value={employeePin} placeholder="••••" onChange={e=>setEmployeePin(e.target.value.replace(/\D/g,''))}/><small>{s.pinHint}</small></label>}{section==='products'&&<><label>{s.kind}<select value={kind} onChange={e=>setKind(e.target.value as CatalogItemKind)}><option value="ingredient">{s.ingredient}</option><option value="finished">{s.finished}</option></select></label><label>{s.category}<select value={category} onChange={e=>setCategory(e.target.value as CatalogItem['category'])}>{categories.map(c=><option key={c} value={c}>{s[c]}</option>)}</select></label>{kind==='finished'&&<label>{s.weight}<input type="number" min="0.001" step="any" value={weight} onChange={e=>setWeight(e.target.value)}/></label>}</>}</div><div className="catalog-checks"><strong>{s.locations}</strong><div>{allSites.map(loc=><label key={loc}><input type="checkbox" checked={locations.includes(loc)} onChange={e=>setLocations(prev=>e.target.checked?[...prev,loc]:prev.filter(x=>x!==loc))}/>{siteLabel[loc]}</label>)}</div><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>{s.active}</label></div>{error&&<p className="catalog-error" role="alert">{error}</p>}<div className="catalog-buttons"><button className="secondary" onClick={reset}>{s.cancel}</button><button className="primary" onClick={submit}>{s.save}</button></div></div>}
   <div className="table-wrap"><table><thead><tr><th>{s.name}</th><th>{section==='products'?s.kind:s.locations}</th><th>{s.active}</th><th/></tr></thead><tbody>{data.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{isItem(p)?(p.kind==='finished'?`${s.counting} · ${p.bagWeightKg} kg` :s.ingredientOnly):p.siteIds.map(x=>siteLabel[x]).join(', ')}</td><td>{p.active?s.active:s.inactive}</td><td><button className="secondary" onClick={()=> isItem(p)?startItem(p):startEmployee(p)}>{s.edit}</button></td></tr>)}</tbody></table>{!data.length&&<p className="empty catalog-empty">{s.none}</p>}</div>
  </div>
}
